language: php
php:
  - '7.0'

install:
  - composer self-update
  - make install

addons:
  code_climate:
    repo_token:245ba3466af2a294a0d8e6b203eff98a86f8d6de

after_script:
- vendor/bin/test-reporter
